import { useState } from 'react';
import { FileText, Code, FileJson, Download, Loader2 } from 'lucide-react';
import { jsPDF } from 'jspdf';
import { ResumeBullet } from '../types';
import { useAppStore, getBulletText } from '../store/useAppStore';
import toast from 'react-hot-toast';
import clsx from 'clsx';

interface ExportPanelProps {
  bullets: ResumeBullet[];
  username: string;
}

type ExportFormat = 'text' | 'pdf' | 'json';

export function ExportPanel({ bullets, username }: ExportPanelProps) {
  const { editedBullets } = useAppStore();
  const [exporting, setExporting] = useState<ExportFormat | null>(null);

  const getBulletTexts = () => {
    return bullets.map(b => getBulletText(b, editedBullets));
  };

  const exportAsText = () => {
    const texts = getBulletTexts();
    const content = texts.map(t => `• ${t}`).join('\n\n');
    
    const blob = new Blob([content], { type: 'text/plain' });
    downloadBlob(blob, `${username}-resume-bullets.txt`);
    toast.success('Exported as plain text!');
  };

  const exportAsPDF = async () => {
    setExporting('pdf');
    
    try {
      const texts = getBulletTexts();
      const doc = new jsPDF();
      
      // Title
      doc.setFontSize(18);
      doc.setFont('helvetica', 'bold');
      doc.text('Technical Experience', 20, 25);
      
      // Subtitle
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100);
      doc.text(`Generated from @${username}'s GitHub activity`, 20, 33);
      
      // Bullets
      doc.setFontSize(11);
      doc.setTextColor(0);
      
      let yPosition = 50;
      const lineHeight = 8;
      const maxWidth = 170;
      const pageHeight = 280;
      
      texts.forEach((text) => {
        const bulletText = `• ${text}`;
        const lines = doc.splitTextToSize(bulletText, maxWidth);
        
        // Check if we need a new page
        if (yPosition + (lines.length * lineHeight) > pageHeight) {
          doc.addPage();
          yPosition = 20;
        }
        
        lines.forEach((line: string) => {
          doc.text(line, 20, yPosition);
          yPosition += lineHeight;
        });
        
        yPosition += 4; // Extra spacing between bullets
      });
      
      // Footer
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text('Generated by ResumeGit - resumegit.dev', 20, 290);
      
      doc.save(`${username}-resume-bullets.pdf`);
      toast.success('Exported as PDF!');
    } catch (error) {
      console.error('PDF export error:', error);
      toast.error('Failed to export PDF');
    } finally {
      setExporting(null);
    }
  };

  const exportAsJSON = () => {
    const exportData = bullets.map(b => ({
      text: getBulletText(b, editedBullets),
      category: b.category,
      technologies: b.tech,
      confidence: b.confidence,
    }));
    
    const content = JSON.stringify({
      username,
      generatedAt: new Date().toISOString(),
      bullets: exportData,
    }, null, 2);
    
    const blob = new Blob([content], { type: 'application/json' });
    downloadBlob(blob, `${username}-resume-bullets.json`);
    toast.success('Exported as JSON!');
  };

  const downloadBlob = (blob: Blob, filename: string) => {
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const exportOptions = [
    {
      id: 'text' as const,
      label: 'Plain Text',
      description: 'Best for ATS systems and copy-pasting',
      icon: FileText,
      action: exportAsText,
    },
    {
      id: 'pdf' as const,
      label: 'PDF Document',
      description: 'Formatted resume section ready for print',
      icon: Code,
      action: exportAsPDF,
    },
    {
      id: 'json' as const,
      label: 'JSON Data',
      description: 'For importing to resume builders',
      icon: FileJson,
      action: exportAsJSON,
    },
  ];

  return (
    <div className="grid sm:grid-cols-3 gap-4">
      {exportOptions.map((option) => {
        const Icon = option.icon;
        const isExporting = exporting === option.id;
        
        return (
          <button
            key={option.id}
            onClick={option.action}
            disabled={exporting !== null}
            className={clsx(
              'p-4 bg-slate-800 border border-slate-700 rounded-lg text-left',
              'hover:border-indigo-500/50 hover:bg-slate-800/80 transition-all',
              'disabled:opacity-50 disabled:cursor-not-allowed',
              'focus:outline-none focus:ring-2 focus:ring-indigo-500'
            )}
          >
            <div className="flex items-center gap-3 mb-2">
              <div className="p-2 bg-slate-700 rounded-lg">
                {isExporting ? (
                  <Loader2 className="w-5 h-5 text-indigo-400 animate-spin" />
                ) : (
                  <Icon className="w-5 h-5 text-indigo-400" />
                )}
              </div>
              <Download className="w-4 h-4 text-slate-500 ml-auto" />
            </div>
            <h4 className="font-medium text-white">{option.label}</h4>
            <p className="text-xs text-slate-500 mt-1">{option.description}</p>
          </button>
        );
      })}
    </div>
  );
}
